##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://nickandplants.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /itrl-data-hub
# location of code, the full url to your github repository
source-code: https://github.com/nickandplants/itrl-data-hub

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Idaho Tree Ring Lab Data Hub
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Digital Archive of the ITRL's Tree Ring Data
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Idaho Tree Ring Lab is committed to creating an open-access, digital archive of tree ring data."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: idaho;tree rings;archive; trees; climate change;climate
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: The Idaho Tree Ring Lab

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: itrl-metadata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Idaho Tree Ring Lab"
organization-link: https://gharley.wixsite.com/itrl
organization-logo-banner: https://static.wixstatic.com/media/53b1a6_7af9291ac381469ea6b5c0f92046a525~mv2_d_1474_3228_s_2.jpg/v1/fill/w_237,h_520,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/53b1a6_7af9291ac381469ea6b5c0f92046a525~mv2_d_1474_3228_s_2.jpg
organization-logo-nav: https://static.wixstatic.com/media/53b1a6_7af9291ac381469ea6b5c0f92046a525~mv2_d_1474_3228_s_2.jpg/v1/fill/w_237,h_520,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/53b1a6_7af9291ac381469ea6b5c0f92046a525~mv2_d_1474_3228_s_2.jpg
##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "G-XXXXXXXXX"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
